// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"refty-backend/internal/app/config"
	"refty-backend/internal/app/container"
	"refty-backend/internal/controller"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	engine := provideGinEngine()
	userCtrl := controller.NewUserCtrl()
	containerContainer := container.NewCtrl(userCtrl)
	configConfig := config.New()
	app := container.NewApp(engine, containerContainer, configConfig)
	return app, nil
}

// wire.go:

func provideGinEngine() *gin.Engine {
	return gin.Default()
}
